### ISSUE TITLE
[Feature]: Support remote caching through the K8sGPT CR

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#113]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  model: gpt-3.5-turbo
  backend: openai
  noCache: false
  version: v0.3.0
  enableAI: true
  # filters:
  #   - Ingress
  secret:
    name: k8sgpt-sample-secret
    key: openai-api-key
 remoteCache:
   credentials:
     name: remote-cache-creds
   bucketName: foo
```

### Benefits

Lets users configure the remote cache through the API
