### ISSUE TITLE
[Feature]: Slack output

### ISSUE THREAD

**Issue by AlexsJones** [k8sgpt-ai/k8sgpt-operator#133]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

No

### Solution Description

In order to provide even more value to users we should give them ability to alert slack 

e.g.

```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: k8sgpt-operator-system
spec:
  model: gpt-3.5-turbo
  backend: openai
  noCache: false
  version: v0.3.0
  enableAI: true
  sinks:
   slack:
     webhook: <WEBHOOK>
  secret:
    name: k8sgpt-sample-secret
    key: openai-api-key
```

The idea is that this would let the user drop in a slack webhook to a pre-configured instance/channel

The main area for refactoring code would be [here](https://github.com/k8sgpt-ai/k8sgpt-operator/blob/main/controllers/k8sgpt_controller.go#L272)

I would suggest adding an additional `sinks.Emit()` style method and a new package `pkg/sinks/slack` where the `sinks` manager would have Slack as a registered sink type, we would also need a `Configure` method that is setup when the webhook is first detected on the CR

### Benefits

Slack messages
