### ISSUE TITLE
[Feature]: Install Grafana dashboard in the namespace where kube-prometheus is located

### ISSUE THREAD

**Issue by yangy30** [k8sgpt-ai/k8sgpt-operator#138]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

Without making any modifications, the dashboard will be installed in the namespace where k8sgpt is located. If the namespaces of kube-prometheus and k8sgpt are different, the dashboard will not work. 

### Solution Description

Adding namespace options in helm

### Benefits

Can make the Grafana dashboard work smoothly.

**Comment by AlexsJones** [comment]
We create a configmap that has a grafana_dashboard label, if you want to enable grafana_dashboards across namespaces you can do that through kube-prometheus. 

When you say the grafana dashboard, are you talking about the configmap we create with the dashboard json?

**Comment by yangy30** [comment]
Yes, when I use the "grafanaDashboard=enabled" parameter, a configmap named "k8sgpt-overview" will be installed in the namespace where k8sgpt is located. If grafana and k8sgpt are not in the same namespace, my grafana cannot be mounted. Therefore, I hope to be able to specify the namespace where this configmap is installed. I don't know if I understand correctly?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "k8sgpt-ai/k8sgpt-operator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月3日(星期六) 凌晨3:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [k8sgpt-ai/k8sgpt-operator] [Feature]: Install Grafana dashboard in the namespace where kube-prometheus is located (Issue #138)





 
We create a configmap that has a grafana_dashboard label, if you want to enable grafana_dashboards across namespaces you can do that through kube-prometheus.
 
When you say the grafana dashboard, are you talking about the configmap we create with the dashboard json?

**Comment by AlexsJones** [comment]
This should be and released right @arbreezy

**Comment by yangy30** [comment]
I would like to add a little more about the installation method of my Prometheus, as I have noticed that there are some differences in the establishment of monitors among different installation methods

I am using the config in the manifests directory, which is different from the kube-prometheus-stack installed by helm

For the GrafanaDashboard, I found that my Grafana cannot automatically scan and load configmap, and can only be manually mounted in deploy. Therefore, I believe it is necessary to install configmap in Prometheus' namespace

Also, if prometheus and k8sgpt are not in the same namespace, Then the administrator needs to add permissions to prometheus, otherwise the monitoring item will not be found
```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-role
  namespace: k8sgpt-operator-system
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - endpoints
  verbs:
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-rolebinding
  namespace: k8sgpt-operator-system
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-role
  apiGroup: rbac.authorization.k8s.io
```
