### ISSUE TITLE
[Bug]: slack report same resource every time analysis

### ISSUE THREAD

**Issue by wujunwei** [k8sgpt-ai/k8sgpt-operator#186]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### K8sGPT Version

v0.3.13

### Steps to reproduce

1. set slack url callback.
```yaml
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-sample
  namespace: openai
spec:
  ai:
    enabled: true
    model: gpt-3.5-turbo
    backend: openai
    secret:
      name: k8sgpt-sample-secret
      key: openai-api-key
    language: english
  noCache: false
  version: v0.3.13
  sink:
    type: slack
    webhook: http://localhost:888/slack
```
2. create some resource which can cause problem.
3. Wait operator to callback.

### Expected behaviour

I think it should be called for 1~3 times or configure it in crd.

### Actual behaviour

call back every time ,because the below code:
```go
	if len(existing.Spec.Error) == len(res.Spec.Error) && reflect.DeepEqual(res.Labels, existing.Labels) {
		existing.Status.LifeCycle = string(NoOpResult)
		err := c.Status().Update(ctx, &existing)
		return NoOpResult, err
	}
```
result.Spec.Error can be different every time ,because it generated by LLM whose generated content is not fixed.

### Additional Information
We can config it like below:
```yaml
  sink:
    type: slack
    webhook: http://localhost:888/slack
    for: 10m
```
If we can determine some strategy , I am happy to work on it :)
