### ISSUE TITLE
[Bug]: Anonymized field does not work

### ISSUE THREAD

**Issue by chnyda** [k8sgpt-ai/k8sgpt-operator#306]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

1. Create a k8sgpt with anonymized set to False.
```
  spec:
    ai:
      anonymized: false
      backend: localai
     ...
```
2. Wait for the controller to add a finalizer
3. The k8sgpt is now like this
```
  spec:
    ai:
      anonymized: true
      backend: localai
     ...
```

### Expected behaviour

The anonymized field should stay as it was during the creation of the object.

### Actual behaviour

When the finalizer is added to the resource and the resource is updated, some fields are set to the default values, probably because of omitempty. One solution is to use pointers instead of pure booleans.
