### ISSUE TITLE
[Question]: Is there a way to remove a filter?

### ISSUE THREAD

**Issue by rwlove** [k8sgpt-ai/k8sgpt-operator#393]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [X] K8sGPT Operator

### Steps to reproduce

```
---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
  namespace: ai
spec:
  ai:
    backend: localai
    baseUrl: http://localai-local-ai.ai.svc.cluster.local:80/v1
    #model: gpt-3.5-turbo                                                                                                                                                     
    model: ggml-gpt4all-j
    secret:
      name: localai-api-key-secret
      key: localai-api-key
  noCache: false
  version: v0.3.29
  filters:
    - Ingress
```

This only adds the ingress filter, but how can I remove processing of ingresses?

### Expected behaviour

remove a filter

### Actual behaviour

add a filter
