### ISSUE TITLE
[Question]: What is the sequence that k8s operator performs checks to the cluster? Is it configurable?

### ISSUE THREAD

**Issue by isioannou** [k8sgpt-ai/k8sgpt-operator#623]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [x] K8sGPT Operator

### K8sGPT Version

v0.3.50

### Kubernetes Version

v1.31

### Steps to reproduce

I have installed k8sgpt operator in an eks cluster configured with localai backend (ollama server with llama3 model) 
```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-ollama
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: llama3
    backend: localai
    baseUrl: http://ollama.ollama.svc.cluster.local:11434/v1 #internal service
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.3.50
```

### Expected behaviour

Operator run and generated the results, but it only run once. I would expect that the operator would make periodic checks to the cluster and create or remove results that have been fixed.

### Actual behaviour

It just run once generated the results and now it is in an idle state as seen from the logs below 

```
manager 2025-03-05T18:59:41Z    INFO    k8sgpt-controller    ending AnalysisStep                                                                                                                                                         │
│ manager 2025-03-05T18:59:41Z    INFO    k8sgpt-controller    starting ResultStatusStep                                                                                                                                                   │
│ manager 2025-03-05T18:59:45Z    INFO    k8sgpt-controller    ending ResultStatusStep                                                                                                                                                     │
│ manager 2025-03-05T18:59:45Z    INFO    k8sgpt-controller    starting RemediationStep                                                                                                                                                    │
│ manager 2025-03-05T18:59:45Z    INFO    k8sgpt-controller    calculateRemediationStep skipped because auto-remediation disabled
```
