### ISSUE TITLE
[Question]: What does autoremediation do in k8sgpt operator?

### ISSUE THREAD

**Issue by y00j** [k8sgpt-ai/k8sgpt-operator#654]
### Checklist

- [x] I've searched for similar issues and couldn't find anything matching
- [x] I've included steps to reproduce the behavior

### Affected Components

- [ ] K8sGPT (CLI)
- [x] K8sGPT Operator

### K8sGPT Version

v0.4.8

### Kubernetes Version

v1.31.3+k3s1

### Host OS and its Version

MacOS 15.2

### Steps to reproduce

Deployed the operator and k8sgpt CR to my cluster. Here is my CR yaml:

```
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-ollama
  namespace: k8sgpt-operator-system
spec:
  ai:
    # autoRemediation:
    #   enabled: true
    #   resources:
    #     - Pod
    #     - Service
    #     - Deployment
    #     - ReplicaSet
    enabled: true
    model: llama3.2:1b
    backend: localai
    baseUrl: http://ollama.ollama.svc.cluster.local:11434/v1
  noCache: false
  remoteCache:
    interplex:
      endpoint: release-interplex-service:8084
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.8
```

### Expected behaviour

Older versions of the operator continually monitored cluster state for errors, and operator reconciliation loop constantly ran with logs.

### Actual behaviour

Does auto remediation need to be enabled for the operator to monitor the cluster for errors? I am seeing this in the operator logs and after that there are no new responses and results to cluster changes.
```
2025-04-07T21:41:54Z    INFO    k8sgpt-controller    starting RemediationStep
2025-04-07T21:41:54Z    INFO    k8sgpt-controller    calculateRemediationStep skipped because auto-remediation disabled
```
