### ISSUE TITLE
Fix error in the example for k8sgpt-local-ai

### ISSUE THREAD

**Issue by bradmccoydev** [k8sgpt-ai/k8sgpt-operator#69]
### Checklist

- [X] I've searched for similar issues and couldn't find anything matching
- [X] I've discussed this feature request in the [K8sGPT Slack](https://k8sgpt.slack.com) and got positive feedback

### Is this feature request related to a problem?

Yes

### Problem Description

In the example for the K8sGPT there spec is wrong. The namespace doesn't exist under spec it should be in metadata.

```yaml
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local-ai
spec:
  namespace: default
  model: gpt-3.5-turbo
  backend: localai
  noCache: false
  version: v0.2.7
  enableAI: true
```

This should be fixed as per: chart/operator/templates/k8sgpt-crd.yaml

### Solution Description

Move namespace under metadata not spec

### Benefits

New people won't have errors when applying example.
